Added altlinux in distrobox
89luca89/distrobox pull request #1512
Opened 2024-08-09 17:09 UTC by Htylol

https://en.wikipedia.org/wiki/ALT_Linux

This is a fairly old Linux distribution based on Linux-Mandrake, using the apt-get and epm package manager, and rpm packages

2024-08-09 17:15 UTC, dervart commented
I will support the request for Alt linux. It would be nice to be able to install it via distrobox

2024-10-10 07:58 UTC, 89luca89 commented
Hi @Htylol thanks for the PR
you should add altlinux container images into the docs, in order to enable the testing of them

2024-10-12 11:00 UTC, 89luca89 requested changes
As commented, we also need the docs changes

2024-10-12 15:42 UTC, Htylol commented
@89luca89 Sorry, I've been offline for a while. Added information about the distribution to compatibility.md
. Is this enough, or is something else needed?

2025-02-04 00:24 UTC, jgarte commented
Hi, what's the latest on this PR? Any updates?

2025-02-05 06:54 UTC, Boria138 commented
PR Is broken

Starting container...                   	 [ OK ]
Installing basic packages...            	 [ OK ]
Setting up devpts mounts...             	 Error: An error occurred

2025-02-05 06:56 UTC, Boria138 commented
```
+ command -v apk
+ command -v apt-get
/usr/bin/apt-get
+ setup_apt
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ '[' 0 -ne 0 ']'
+ rm -f /etc/dpkg/dpkg.cfg.d/excludes
+ apt-get update
Get:1 http://ftp.altlinux.org Sisyphus/x86_64 release [4233B]
Get:2 http://ftp.altlinux.org Sisyphus/x86_64-i586 release [1680B]
Get:3 http://ftp.altlinux.org Sisyphus/noarch release [2854B]
Fetched 8767B in 0s (35.4kB/s)
Get:1 http://ftp.altlinux.org Sisyphus/x86_64/classic pkglist [26.3MB]
Get:2 http://ftp.altlinux.org Sisyphus/x86_64/classic release [147B]
Get:3 http://ftp.altlinux.org Sisyphus/x86_64-i586/classic pkglist [17.9MB]
Get:4 http://ftp.altlinux.org Sisyphus/x86_64-i586/classic release [152B]
Get:5 http://ftp.altlinux.org Sisyphus/noarch/classic pkglist [7650kB]
Get:6 http://ftp.altlinux.org Sisyphus/noarch/classic release [147B]
Fetched 51.9MB in 1m26s (599kB/s)
Reading Package Lists...
Building Dependency Tree...
+ apt-get install -y bash
Reading Package Lists...
Building Dependency Tree...
bash is already the newest version.
0 upgraded, 0 newly installed, 0 removed and 27 not upgraded.
+ deps='
		bash
		apt-utils
		bash-completion
		bc
		bzip2
		curl
		dialog
		diffutils
		findutils
		gnupg
		gnupg2
		gpgsm
		hostname
		iproute2
		iputils-ping
		keyutils
		language-pack-en
		less
		libcap2-bin
		libkrb5-3
		libnss-mdns
		libnss-myhostname
		libvte-2.9*-common
		libvte-common
		locales
		lsof
		man-db
		manpages
		mtr
		ncurses-base
		openssh-client
		passwd
		pigz
		pinentry-curses
		procps
		rsync
		sudo
		tcpdump
		time
		traceroute
		tree
		tzdata
		unzip
		util-linux
		wget
		xauth
		xz-utils
		zip
		libgl1
		libegl-mesa0
		libegl1-mesa
		libgl1-mesa-glx
		libegl1
		libglx-mesa0
		libvulkan1
		mesa-vulkan-drivers
	'
++ grep Package:
++ sort -u
++ cut '-d ' -f2-
++ apt-cache show bash apt-utils bash-completion bc bzip2 curl dialog diffutils findutils gnupg gnupg2 gpgsm hostname iproute2 iputils-ping keyutils language-pack-en less libcap2-bin libkrb5-3 libnss-mdns libnss-myhostname 'libvte-2.9*-common' libvte-common locales lsof man-db manpages mtr ncurses-base openssh-client passwd pigz pinentry-curses procps rsync sudo tcpdump time traceroute tree tzdata unzip util-linux wget xauth xz-utils zip libgl1 libegl-mesa0 libegl1-mesa libgl1-mesa-glx libegl1 libglx-mesa0 libvulkan1 mesa-vulkan-drivers
+ apt-get install -y bash
Reading Package Lists...
Building Dependency Tree...
bash is already the newest version.
0 upgraded, 0 newly installed, 0 removed and 27 not upgraded.
+ '[' -e /etc/locale.gen ']'
+ '[' '!' -e /usr/share/zoneinfo/UTC ']'
+ apt-get --reinstall install tzdata
Reading Package Lists...
Building Dependency Tree...
The following NEW packages will be installed:
  tzdata
0 upgraded, 1 newly installed, 0 removed and 27 not upgraded.
Need to get 390kB of archives.
After unpacking 909kB of additional disk space will be used.
Get:1 http://ftp.altlinux.org Sisyphus/noarch/classic tzdata 2024a-alt1:sisyphus+344801.100.1.1@1712691698 [390kB]
Fetched 390kB in 1s (387kB/s)
Committing changes...
Preparing...                            ################################# [100%]
Updating / installing...
1: tzdata-2024a-alt1                    ################################# [100%]
Done.
+ '[' -n '' ']'
+ touch /.containersetupdone
++ command -v bash
+ SHELL=/usr/bin/bash
+ /usr/bin/distrobox-host-exec -Y test
+ :
+ command -v xdg-open
+ mkdir -p /usr/local/bin/
+ ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open
+ command -v flatpak
+ ln -sf /usr/bin/distrobox-host-exec /usr/bin/flatpak
+ su --help
+ grep -q pty
/usr/bin/entrypoint: line 1739: su: command not found
+ cat
+ chmod +x /usr/local/bin/su
+ printf 'distrobox: Setting up devpts mounts...\n'
distrobox: Setting up devpts mounts...
+ grep -q tty /etc/group
+ mount -t devpts devpts -o noexec,nosuid,newinstance,ptmxmode=0666,mode=0620,gid=tty /dev/pts/
/usr/bin/entrypoint: line 1766: mount: command not found
+ '[' 127 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred
+ stat /run/host/etc/shadow
++ stat -c %u /run/host/etc/shadow
+ '[' 65534 = 0 ']'
+ '[' -f /run/host/etc/locale.conf ']'
++ grep -e '^LANG=' /run/host/etc/locale.conf
++ sed s/LANG=//
++ sed 's/"//g'
++ sed 's/'\''//g'
+ HOST_LOCALE=ru_RU.UTF-8
++ echo ru_RU.UTF-8
++ sed -n 's/^[^.]*\.\(.*\)$/\1/p'
+ HOST_LOCALE_ENCODING=UTF-8
++ echo ru_RU.UTF-8
++ sed -n 's/^\([^.]*\)\..*$/\1/p'
+ HOST_LOCALE_LANG=ru_RU
+ '[' -z ru_RU.UTF-8 ']'
+ '[' ru_RU.UTF-8 = C.UTF-8 ']'
+ '[' -n '' ']'
+ printf 'distrobox: Installing basic packages...\n'
distrobox: Installing basic packages...
++ basename bash
+ shell_pkg=bash
+ '[' bash = ash ']'
+ missing_packages=0
+ dependencies='
	bc
	bzip2
	chpasswd
	curl
	diff
	find
	findmnt
	gpg
	hostname
	less
	lsof
	man
	mount
	passwd
	pigz
	pinentry
	ping
	ps
	rsync
	script
	ssh
	sudo
	time
	tree
	umount
	unzip
	useradd
	wc
	wget
	xauth
	zip
	bash
'
+ for dep in ${dependencies}
+ command -v bc
+ missing_packages=1
+ break
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin:/sbin:/usr/bin:/usr/sbin
+ command -v apt-get
/usr/bin/apt-get
+ setup_deb_exceptions
+ setup_pkg_manager_hooks
+ '[' -d /etc/dpkg/dpkg.cfg.d/ ']'
+ '[' 0 -eq 0 ']'
+ cat
+ cat
+ chmod +x /etc/distrobox-pre-hook.sh /etc/distrobox-post-hook.sh
+ '[' 0 -eq 0 ']'
+ mkdir -p /etc/dpkg/dpkg.cfg.d/
+ printf ''
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /etc/localtime
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /var/lib/systemd/coredump
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /var/log/journal
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /etc/host.conf
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /etc/machine-id
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /media
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /mnt
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /run/libvirt
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /run/media
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /run/netconfig/
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /run/systemd/journal
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /run/systemd/resolve/
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /run/systemd/seats
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /run/systemd/sessions
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /run/systemd/users
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /run/udev
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /var/lib/libvirt
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS}
+ printf 'path-exclude %s/*\n' /var/mnt
+ '[' -d /etc/apt/apt.conf.d/ ']'
+ printf 'DPkg::Pre-Invoke {/etc/distrobox-pre-hook.sh};\n'
+ printf 'DPkg::Post-Invoke {/etc/distrobox-post-hook.sh};\n'
+ '[' 0 -ne 0 ']'
+ '[' 1 -ne 0 ']'
+ command -v apk
+ command -v apt-get
/usr/bin/apt-get
+ setup_apt
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ '[' 0 -ne 0 ']'
+ rm -f /etc/dpkg/dpkg.cfg.d/excludes
+ apt-get update
Get:1 http://ftp.altlinux.org Sisyphus/x86_64 release [4233B]
Get:2 http://ftp.altlinux.org Sisyphus/x86_64-i586 release [1680B]
Get:3 http://ftp.altlinux.org Sisyphus/noarch release [2854B]
Fetched 8767B in 0s (28.9kB/s)
Hit http://ftp.altlinux.org Sisyphus/x86_64/classic pkglist
Hit http://ftp.altlinux.org Sisyphus/x86_64/classic release
Hit http://ftp.altlinux.org Sisyphus/x86_64-i586/classic pkglist
Hit http://ftp.altlin [...]

2025-02-13 06:50 UTC, Boria138 commented
> Hi, what's the latest on this PR? Any updates?

I built distrobox with this PR in ALT Sisyphus, so if you need distrobox with ALT Linux support it is available in ALT Linux, for building in p11 I will wait until the PR is officially adopted, maybe by then bugs will pop up, but so far during the week that this PR is in the repositories no bugs have been detected

2025-05-04 10:08 UTC, Boria138 commented
@Htylol pr need fix

```
> sudo distrobox enter alt
[sudo] password for x1z53:
Running distrobox-enter via SUDO/DOAS is not supported. Instead, please try running:
  distrobox-enter --root alt
/bin/distrobox-enter: строка 69: [: : ожидается целочисленное выражение
```

```
> distrobox enter --root alt
/usr/bin/distrobox-enter: eval: строка 553: синтаксическая ошибка рядом с неожиданным маркером «;»
```

2025-05-06 18:21 UTC, Boria138 commented
Oh my podman is broken, patch is worked sorry

2025-06-22 09:07 UTC, Rirusha commented
@89luca89, What is missing to accept?

2025-08-20 12:10 UTC, dottorblaster requested changes
Besides what I highlighted, this PR looks very good. Could you just address this last feedback?

Thank you so much for waiting, we're really looking forward to ALT Linux + Distrobox! ❤️

2025-08-20 12:10 UTC, dottorblaster commented on distrobox-init
> +		fi
Could we just leverage `command -v apt && command -v rpm` as a condition to assume apt-rpm is present?

2025-08-20 12:24 UTC, Boria138 commented on distrobox-init
> +		fi
> Could we just leverage `command -v apt && command -v rpm` as a condition to assume apt-rpm is present?

No apt-rpm bin called apt-get

2025-08-20 12:30 UTC, dottorblaster commented on distrobox-init
> +		fi
So ALT Linux _does not_ have an `rpm` command at all?

2025-08-20 13:00 UTC, dottorblaster commented on distrobox-init
> +		fi
I took some time to download an ALT Linux image and spin up a vm:

<img width="1114" height="729" alt="Image" src="https://github.com/user-attachments/assets/676ff46c-b6f6-42a9-8e0e-111816afc062" />

`command -v apt-get && command -v rpm` should work.

2025-08-21 05:58 UTC, Htylol commented
> Besides what I highlighted, this PR looks very good. Could you just address this last feedback?
> 
> Thank you so much for waiting, we're really looking forward to ALT Linux + Distrobox! ❤️
Changed the check to command -v rpm (apt-get is already checked), synchronized my pr with the latest changes in distrobox.

2025-08-21 07:33 UTC, dottorblaster commented
@Htylol I noticed this is marked as draft, can I review? :smile:

2025-08-21 08:36 UTC, Htylol commented
@dottorblaster Made some minor changes, now removed draft

2025-08-21 09:25 UTC, dottorblaster approved these changes
Great! Looks good to me, thank you for your contribution! ❤️ 🚀

2025-08-21 10:29 UTC, 89luca89 commented on distrobox-init
> +	if grep -q "altlinux" /etc/os-release; then
Is this altlinux only? Or any aptrpm distro has this problem?

If altlinux only maybe you can simply check for the presence of the "control" command, as it seems altlinux specific
This way we support derivatives of altlinux automatically

2025-08-21 12:40 UTC, Htylol commented on distrobox-init
> +	if grep -q "altlinux" /etc/os-release; then
> Это только альтлинукс? Или в каком-либо дистрибутиве aptrpm есть эта проблема?
> 
> Если только altlinux, возможно, вы можете просто проверить наличие команды «control», так как она, похоже, специфична для altlinux Таким образом, мы автоматически поддерживаем производные от altlinux

Changed ```if grep -q "altlinux" /etc/os-release; then``` to ```if command -v control; then``` (tested, works). I haven't checked other distributions with apt-get package manager and rpm packages (there aren't many of them, or they use altlinux as a base).

2025-08-21 13:04 UTC, 89luca89 approved these changes

2025-08-21 13:06 UTC, dottorblaster commented on distrobox-init
> +	if grep -q "altlinux" /etc/os-release; then
Thanks for bearing with us!

2025-08-21 13:07 UTC, merged