Fix distrobox-enter and distrobox-rm to handle containers that have environment variables shoter than 5 symbols
89luca89/distrobox pull request #1545
Opened 2024-09-04 05:51 UTC by senioroman4uk

When I was trying to use distrobox with rocm/pytorch:latest I've noticed the following error 
```
Error: template: inspect:3:27: executing "inspect" at <slice . 0 5>: error calling slice: index out of range: 5
```

It turns out this image has an environmental variable CI=1, that causes an exception when distrobox-enter / distrobox-rm is used with this docker image

Added some additional ifs to the corresponding commands to handle this case

2024-09-04 06:04 UTC, senioroman4uk commented
Fixes #1546

2024-10-05 20:42 UTC, softmoth approved these changes
Looks good to me!

2024-10-05 20:47 UTC, softmoth requested changes
Actually, it's probably better to use the [`startswith` function](https://jqlang.github.io/jq/manual/#startswith).

2024-10-09 19:32 UTC, mirkobrombin approved these changes

2024-10-10 07:48 UTC, 89luca89 commented
Thanks @senioroman4uk for the PR and thanks @mirkobrombin for reviewing!

2024-10-10 07:49 UTC, merged