Eval the call to $container_manager rm instead of a plain call
89luca89/distrobox pull request #1564
Opened 2024-09-20 10:30 UTC by dcermak

The shell tries to execute `$container_manager` directly, which fails if it is a composite command like `sudo podman` as that is not a valid binary. By instead evaluating the whole command, we circumvent this issue.

This fixes https://github.com/89luca89/distrobox/issues/1542

2024-10-05 20:34 UTC, softmoth requested changes
The source of this problem is that `IFS` is set in `cleanup_exports`, and not restored, so normal word splitting does not happen.

The correct fix is to restore IFS at the bottom of `cleanup_exports`, and no `eval` is required. The other scripts use `unset IFS` to restore it, which should be portable enough.

I think it's worth auditing the rest of the scripts, too, and creating a consistent method for restoring IFS. Some places use `unset IFS` (correct), others use `IFS=" "` (it's incorrect, but kind of works) at the site of needing to split on spaces.

I propose every use of `IFS=X` should be paired with `unset IFS`. And uses of `IFS=" "` should be removed or replaced with `unset IFS` when at the top of a loop body.

2024-10-07 13:32 UTC, dcermak commented
> The source of this problem is that `IFS` is set in `cleanup_exports`, and not restored, so normal word splitting does not happen.
> 
> The correct fix is to restore IFS at the bottom of `cleanup_exports`, and no `eval` is required. The other scripts use `unset IFS` to restore it, which should be portable enough.

Isn't it there already? https://github.com/89luca89/distrobox/blob/c05b6a43769bfa56d572a457f1420e0e2589fe3b/distrobox-rm#L329

2024-10-09 19:21 UTC, mirkobrombin commented
Thanks for your contribution. Can you clarify which is the case when this happens? Using the `--root` flag (correct way to use podman as root) I don't have the problem. Can you explain your use case so I can evaluate?

2024-10-10 07:50 UTC, 89luca89 commented
This is already fixed in `main` by 952ffaa75717dcd8ba05962b945af80057fdba88

2024-10-10 07:50 UTC, closed without merging