create: keep $SHELL directory prefix
89luca89/distrobox pull request #1584
Opened 2024-10-10 14:37 UTC by timwa0669

When $SHELL variable does not contain directory prefix like 'zsh', the 'script ...' command run via python may failed, causing compatibiltiy dropping.

This bug was found while using Petalinux 2020.1 SDK, running 'petalinux-config -c kernel'.

2024-10-10 14:46 UTC, timwa0669 commented
Should this change become optional? Regarding the following situation I list below, maybe this PR will cause the introduction of a new issue.

Assume I use zsh, if the shell executables are in different places between host and containers:
Host: the 'zsh' can be found under /bin
Container: the 'zsh' can be found under /usr/bin, not /bin

2024-10-10 15:08 UTC, 89luca89 commented
> Should this change become optional? Regarding the following situation I list below, maybe this PR will cause the introduction of a new issue.
> 
> Assume I use zsh, if the shell executables are in different places between host and containers: Host: the 'zsh' can be found under /bin Container: the 'zsh' can be found under /usr/bin, not /bin

yes that's the reason this exists

SHELL is then set in the `init` to the regular path afterwards using profiles
https://github.com/89luca89/distrobox/blob/21661400fa65e72b4b160ae905aaa12644538a38/distrobox-init#L2006

2024-10-10 16:20 UTC, timwa0669 commented
> > Should this change become optional? Regarding the following situation I list below, maybe this PR will cause the introduction of a new issue.
> > Assume I use zsh, if the shell executables are in different places between host and containers: Host: the 'zsh' can be found under /bin Container: the 'zsh' can be found under /usr/bin, not /bin
> 
> yes that's the reason this exists
> 
> SHELL is then set in the `init` to the regular path afterwards using profiles
> 
> https://github.com/89luca89/distrobox/blob/21661400fa65e72b4b160ae905aaa12644538a38/distrobox-init#L2006

Thanks for your comment! I know why the $SHELL isn't updated. I use zsh. Zsh won't source /etc/profile.d/*.sh on Ubuntu 18.04.6 after entering the container. So the $SHELL var was not updated.

Maybe we should change the place of 'export SHELL="\$(getent passwd "\${USER}" | cut -f 7 -d :)" ' to support non-bash shells?

2024-10-11 06:25 UTC, 89luca89 commented
> Thanks for your comment! I know why the $SHELL isn't updated. I use zsh. Zsh won't source /etc/profile.d/*.sh on Ubuntu 18.04.6 after entering the container. So the $SHELL var was not updated.
> 
> Maybe we should change the place of 'export SHELL="$(getent passwd "${USER}" | cut -f 7 -d :)" ' to support non-bash shells? (Or any way to let non-bash shells to source /etc/profile.d/distrobox_*.sh?)

I don't know about zsh, but I'd say we need to find the equivalent file where to put the source

2024-10-12 08:44 UTC, 89luca89 requested changes
This won't work
let's find a way to make zsh source the profile correctly

2024-10-19 03:27 UTC, closed without merging