init: If user already exists in /etc/passwd set props again, do not skip
89luca89/distrobox pull request #176
Opened 2022-02-19 23:40 UTC by ennec-e

This fixes a bug #175 where home field in /etc/passwd diverges from value of $HOME
which then causes unexpected behaviour.
When user is pre-prepopulated due to some reason the old behaviour was to skip useradd.
So path in /etc/passwd could be different than one manually set (ex. when user asks for custom home).

Fix bug by force-setting properties with _usermod_ if user already exists.

2022-02-20 15:20 UTC, 89luca89 commented
Hey @ennec-e thanks for the contribution!

Just a couple of comments on this before merging, also does this fix #175 for you?

2022-02-20 15:22 UTC, 89luca89 requested changes

2022-02-20 15:22 UTC, 89luca89 commented on distrobox-init
> +else
Let's just add a couple of comments here
this situation is presented when podman or docker already creates the user for us, so we find it already present

2022-02-20 15:22 UTC, 89luca89 commented on distrobox-init
> +	if ! usermod \
Given that we're adding usermod command, it would be nice if you add it to the list of checks in lines 194-197

2022-02-23 10:20 UTC, ennec-e commented
> also does this fix #175 for you?

Yes. I've been using distrobox locally with this patch. It does resolve #175 for me.
I'll get on to making the changes you requested now.

2022-02-23 18:10 UTC, merged