Remove --name since never used
89luca89/distrobox pull request #821
Opened 2023-06-24 15:50 UTC by mirkobrombin

I might be wrong but the `--name` flag is never used in the source:

```
distrobox rm --name apx-alpine --force
ERROR: Invalid flag '--name'

distrobox version: 1.5.0.2

Usage:

	distrobox-rm [-f/--force] container-name [container-name1 container-name2 ...]

Options:

	--name/-n:		name for the distrobox
	--force/-f:		force deletion
	--rm-home:		remove the mounted home if it differs from the host user's one
	--root/-r:		launch podman/docker with root privileges. Note that if you need root this is the preferred
				way over "sudo distrobox" (note: if using a program other than 'sudo' for root privileges is necessary,
				specify it through the DBX_SUDO_PROGRAM env variable, or 'distrobox_sudo_program' config variable)
	--help/-h:		show this message
	--verbose/-v:		show more verbosity
	--version/-V:		show version
```

2023-06-28 20:12 UTC, bubuntux commented
@mirkobrombin  probably also want to remove it from the md file (distrobox-rm.md)

2023-06-28 20:19 UTC, mirkobrombin commented
> @mirkobrombin probably also want to remove it from the md file (distrobox-rm.md)

Thanks, I missed it.

2023-08-03 00:05 UTC, luc14n0 requested changes
Yeah, that option flags is currently not implemented in the script. So, for me, it makes sense to drop those `--name` mentions.

If you could also drop it from the manpages:

``` sh
$ rg 'distrobox[- ]rm --name'
man/man1/distrobox.1
1818:distrobox-rm --name container-name [--force]

man/man1/distrobox-rm.1
51:distrobox-rm --name container-name [--force]

docs/usage/distrobox-rm.md
27:     distrobox-rm --name container-name [--force]
```

Then we could hope and wait for Luca's final word on this change :+1:

2023-08-03 07:49 UTC, 89luca89 commented
Thanks a lot! :heart:

2023-08-03 07:50 UTC, merged